"""
Game settings
"""
import pygame
import pymunk
import pymunk.pygame_util

# Settings Magic Numbers
SCREEN_WIDTH = 1250
SCREEN_HEIGHT = 750
SCREEN_COLOR = (0, 0, 0)

GRAVITY_X = 0
GRAVITY_Y = 0

UPDATES_PER_SECOND = 60.0
FRAMES_PER_SECOND = 60

PADDING = 5

# Files
SCREEN_FILE_DIFF = 50
SCREEN_FILE_0 = 0 + PADDING*10
SCREEN_FILE_1 = SCREEN_FILE_0 - SCREEN_FILE_DIFF
SCREEN_FILE_2 = SCREEN_FILE_1 - SCREEN_FILE_DIFF
SCREEN_FILE_3 = SCREEN_FILE_2 - SCREEN_FILE_DIFF
SCREEN_FILE_4 = SCREEN_FILE_3 - SCREEN_FILE_DIFF
SCREEN_FILE_5 = SCREEN_FILE_4 - SCREEN_FILE_DIFF
SCREEN_FILE_6 = SCREEN_FILE_5 - SCREEN_FILE_DIFF
SCREEN_FILE_7 = SCREEN_FILE_6 - SCREEN_FILE_DIFF
SCREEN_FILE_8 = SCREEN_FILE_7 - SCREEN_FILE_DIFF
SCREEN_FILE_9 = SCREEN_FILE_8 - SCREEN_FILE_DIFF

# Ranks
SCREEN_RANK_DIFF = 275
SCREEN_RANK_0 = 0 + PADDING*10
SCREEN_RANK_1 = SCREEN_RANK_0 + SCREEN_RANK_DIFF
SCREEN_RANK_2 = SCREEN_RANK_1 + SCREEN_RANK_DIFF
SCREEN_RANK_3 = SCREEN_RANK_2 + SCREEN_RANK_DIFF
SCREEN_RANK_4 = SCREEN_RANK_3 + SCREEN_RANK_DIFF
SCREEN_RANK_5 = SCREEN_RANK_4 + SCREEN_RANK_DIFF
SCREEN_RANK_6 = SCREEN_RANK_5 + SCREEN_RANK_DIFF
SCREEN_RANK_7 = SCREEN_RANK_6 + SCREEN_RANK_DIFF
SCREEN_RANK_8 = SCREEN_RANK_7 + SCREEN_RANK_DIFF
SCREEN_RANK_9 = SCREEN_RANK_8 + SCREEN_RANK_DIFF

# Test Magic Numbers
TEST_ENEMY_NUMBERS = 5
